[package]
name = "mainshit"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest ={version = "0.11", features = ["blocking" , "json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
ratatui = {version = "0.26.1", features = ["crossterm"]}
crossterm = "0.27.0"
